version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: webwise_php
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "3003:8000"
    # For install project
    # Move setup-composer.sh from src before creation
    command: /bin/bash -c "export COMPOSER_HOME=/usr/local/bin && composer config --global github-oauth.github.com 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 && cd src && composer create-project laravel/laravel . && mv ../setup-composer.sh ./ && ./setup-composer.sh"
    #command: /bin/bash -c "./src/setup-composer.sh"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: 'discover_client_host=true client_host=host.docker.internal log_level=0'
      PHP_IDE_CONFIG: 'serverName=host.docker.internal'
    working_dir: /var/www
    volumes:
       - ./:/var/www:rw
       - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
       - ./docker/php/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webwise_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    user: root
    image: mysql:latest
    container_name: webwise_mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    tty: true
    ports:
      - "7776:3306"
    environment:
      MYSQL_DATABASE: webwise
      MYSQL_USER: webwise
      MYSQL_PASSWORD: webwise
      MYSQL_ROOT_PASSWORD: webwise
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webwise_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 7760:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
